/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsProjectIdRouteImport } from './routes/projects.$projectId'
import { Route as ProjectsProjectIdLinksLinkIdRouteImport } from './routes/projects.$projectId_.links.$linkId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdRoute = ProjectsProjectIdRouteImport.update({
  id: '/projects/$projectId',
  path: '/projects/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdLinksLinkIdRoute =
  ProjectsProjectIdLinksLinkIdRouteImport.update({
    id: '/projects/$projectId_/links/$linkId',
    path: '/projects/$projectId/links/$linkId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/projects/$projectId/links/$linkId': typeof ProjectsProjectIdLinksLinkIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/projects/$projectId/links/$linkId': typeof ProjectsProjectIdLinksLinkIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/projects/$projectId_/links/$linkId': typeof ProjectsProjectIdLinksLinkIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/projects/$projectId' | '/projects/$projectId/links/$linkId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/projects/$projectId' | '/projects/$projectId/links/$linkId'
  id:
    | '__root__'
    | '/'
    | '/projects/$projectId'
    | '/projects/$projectId_/links/$linkId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProjectsProjectIdRoute: typeof ProjectsProjectIdRoute
  ProjectsProjectIdLinksLinkIdRoute: typeof ProjectsProjectIdLinksLinkIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId': {
      id: '/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof ProjectsProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId_/links/$linkId': {
      id: '/projects/$projectId_/links/$linkId'
      path: '/projects/$projectId/links/$linkId'
      fullPath: '/projects/$projectId/links/$linkId'
      preLoaderRoute: typeof ProjectsProjectIdLinksLinkIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProjectsProjectIdRoute: ProjectsProjectIdRoute,
  ProjectsProjectIdLinksLinkIdRoute: ProjectsProjectIdLinksLinkIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
